# Generated by Django 2.0.4 on 2018-04-18 03:00

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupCtrl',
            fields=[
                ('Fid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Fschema', models.CharField(default='', max_length=128, verbose_name='库名')),
                ('Ftable_name', models.CharField(default='', max_length=128, verbose_name='表名')),
                ('Ftype', models.CharField(choices=[('0', '全量'), ('1', '按日切片'), ('2', '按月切片'), ('3', '按年切片'), ('4', '指定区间'), ('5', '拉链表'), ('6', '指定条件')], default='0', max_length=1, verbose_name='备份类型')),
                ('Fsplit_field', models.CharField(blank=True, default='', max_length=1024, verbose_name='拆分条件')),
                ('Fbackup_status', models.CharField(choices=[('0', '备份失败'), ('1', '备份成功'), ('2', '备份中')], default='0', max_length=1, verbose_name='备份状态')),
                ('Fdata_begin_date', models.DateTimeField(default=datetime.datetime(1990, 11, 26, 0, 0), verbose_name='数据开始日期')),
                ('Fbackup_strategy', models.CharField(default='0', max_length=1, verbose_name='更新策略')),
                ('Fbackup_interval', models.PositiveIntegerField(default=1, verbose_name='备份时间间隔（天）')),
                ('Flast_date', models.DateField(default=datetime.datetime(1990, 11, 26, 0, 0), verbose_name='最后一次备份日期')),
                ('Fpriority', models.CharField(default='0', max_length=1, verbose_name='优先级')),
                ('Fserver_ip', models.GenericIPAddressField(null=True, verbose_name='备份服务器IP地址')),
                ('Fserver_info', models.CharField(default='Backup001', max_length=32, verbose_name='服务器描述')),
                ('Fmodify_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='变更时间')),
            ],
            options={
                'verbose_name': '备份控制',
                'verbose_name_plural': '备份控制',
                'db_table': 'backup_ctrl',
                'ordering': ['-Fmodify_time'],
            },
        ),
        migrations.CreateModel(
            name='FileInfo',
            fields=[
                ('Fid', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('Fschema', models.CharField(default='', max_length=128, verbose_name='库名')),
                ('Ftable_name', models.CharField(default='', max_length=128, verbose_name='表名')),
                ('Ffile_name', models.CharField(default='', max_length=255, verbose_name='文件名')),
                ('Ffile_version', models.CharField(default='N', max_length=1, verbose_name='文件版本')),
                ('Fcondition', models.CharField(default='', max_length=1024, verbose_name='导出条件')),
                ('Frebackup', models.CharField(default='N', max_length=1, verbose_name='是否需要重新备份')),
                ('Frecord_num', models.PositiveIntegerField(default=0, verbose_name='记录条数')),
                ('Fbytes', models.PositiveIntegerField(default=0, verbose_name='文件大小')),
                ('Fmd5', models.CharField(default='', max_length=32, verbose_name='md5')),
                ('Fserver_ip', models.GenericIPAddressField(null=True, verbose_name='备份服务器IP地址')),
                ('Fserver_info', models.CharField(default='Backup001', max_length=32, verbose_name='服务器描述')),
                ('Fstatus', models.CharField(choices=[('0', '导出失败'), ('1', '导出成功'), ('2', '导出中')], default='0', max_length=1, verbose_name='导出状态')),
                ('Fdate', models.DateField(auto_now=True, verbose_name='生成日期')),
                ('Ftime', models.TimeField(auto_now=True, verbose_name='生成时间')),
            ],
            options={
                'verbose_name': '文件信息',
                'verbose_name_plural': '文件信息',
                'db_table': 'file_info',
                'ordering': ['-Fdate'],
            },
        ),
    ]
