DROP FOREIGN TABLE IF EXISTS PD_GDSFILE.PD_DATA_SEC_OPT_VOLATILITY;
CREATE FOREIGN TABLE PD_GDSFILE.PD_DATA_SEC_OPT_VOLATILITY(
TRADE_DATE     TIMESTAMP
,OPT_CODE     CHAR(8)
)server gsmpp_server options(location 'gsfs://127.0.0.1:8888',
format 'TEXT',encoding 'GBK',delimiter '|',null '',NOESCAPING 'ON')write only;


START TRANSACTION;
INSERT INTO PD_GDSFILE.PD_DATA_SEC_OPT_VOLATILITY
SELECT 
TRADE_DATE
,OPT_CODE
FROM PD_DATA.SEC_OPT_VOLATILITY 
WHERE TRADE_DATE='20161230';
END;